source 'https://rubygems.org'

gem 'middleman', github: 'middleman/middleman'
gem 'middleman-autoprefixer', '~> 2.7'
gem 'middleman-condenser', github: 'bemky/middleman-condenser', branch: 'dedup_assets'
gem 'condenser', github: 'malomalo/condenser'
gem 'tzinfo-data', platforms: [:mswin, :mingw, :jruby, :x64_mingw]
gem 'wdm', '~> 0.1', platforms: [:mswin, :mingw, :x64_mingw]
gem 'uniform-ui', require: 'uniform', github: 'bemky/uniform'

gem 'github-markup'
gem 'commonmarker'
gem 'middleman-syntax', github: 'tnir/middleman-syntax', branch: "haml-6.x"