import { AutoGrid, Modal, Floater, Table, Tooltip, Dropdown, NotificationCenter, Dropzone, Spreadsheet, ContentArea, Resizer, SearchField, Select } from './komps.js';

AutoGrid.define()
Modal.define()
Floater.define()
Table.define()
Tooltip.define()
Dropdown.define()
NotificationCenter.define()
Dropzone.define()
Spreadsheet.define()
ContentArea.define()
Resizer.define()
SearchField.define()
Select.define()
